# Keras로 Linear&Logistic Regression 맛보기!

### Kaggle Link for exercise :
* [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) : 

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
# 텐서플로우 설치
# !pip install tensorflow --user

In [2]:
!pip list

Package                            Version
---------------------------------- -------------------
absl-py                            1.0.0
aioredis                           1.3.1
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.3
anaconda-project                   0.9.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
asgiref                            3.4.1
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.2.1
astunparse                         1.6.3
async-generator                    1.10
async-timeout                      4.0.2
atomicwrites                       1.4.0
attrs                              20.3.0
autobahn                           21.11.1
Automat                            20.2.0
autopep8                           1.

In [3]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [4]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [5]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [6]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 421ms/step - loss: 826.2627
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 825.5754
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 824.8885
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 824.2018
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 823.5154
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 822.8295
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 822.1437
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 821.4584
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 820.7733
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 820.0886


In [7]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [8]:
model.predict(x).reshape(-1)

array([ 9.99859627e-03, -6.43082440e-01, -1.29616356e+00, -1.94924462e+00,
       -2.60232568e+00, -3.25540662e+00, -3.90848780e+00, -4.56156874e+00,
       -5.21464968e+00, -5.86773062e+00, -6.52081156e+00, -7.17389297e+00,
       -7.82697392e+00, -8.48005581e+00, -9.13313675e+00, -9.78621769e+00,
       -1.04392986e+01, -1.10923796e+01, -1.17454605e+01, -1.23985415e+01],
      dtype=float32)

## Now, Your turn!

In [9]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [10]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [18]:
x.shape, y.shape

((20,), (20,))

In [11]:
# 1번 모델 초기화
keras.backend.clear_session()

# 2번 모델 생성 : Sequential()
model = keras.Sequential()

# 3번 모델 블록 조합 : .add()
model.add(keras.layers.Input(1))
model.add(keras.layers.Dense(1))

# 4번 모델 컴파일
model.compile(loss='mse', optimizer='adam')

In [12]:
# 5번 모델 훈련
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 347ms/step - loss: 1741.9714
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 1740.9856
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 1740.0002
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 1739.0150
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 1738.0303
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 1737.0459
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 1736.0613
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 1735.0775
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 1734.0941
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 1733.1110


In [17]:
model.evaluate(x,y)

1/1 [==============================] - 0s 131ms/step - loss: 1732.1279


1732.1279296875

In [13]:
# 6번 예측
y_pred = model.predict(x).reshape(-1)

print(y)
print(y_pred)

[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]
[-9.9989548e-03  1.4757634e+00  2.9615257e+00  4.4472880e+00
  5.9330506e+00  7.4188132e+00  8.9045744e+00  1.0390337e+01
  1.1876100e+01  1.3361862e+01  1.4847625e+01  1.6333387e+01
  1.7819149e+01  1.9304913e+01  2.0790674e+01  2.2276438e+01
  2.3762199e+01  2.5247961e+01  2.6733725e+01  2.8219486e+01]


## Quick Logistic Regression!

In [19]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [20]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [21]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

In [23]:
# 데이터를 넣어서 학습시키자!
model.fit(x[:15], y[:15], epochs=10, verbose=1)

# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]).reshape(-1))

Epoch 1/10
1/1 [==============================] - 0s 8ms/step - loss: 4.8825 - accuracy: 0.4000
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 4.8789 - accuracy: 0.4000
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 4.8753 - accuracy: 0.4000
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 4.8717 - accuracy: 0.4000
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8681 - accuracy: 0.4000
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8645 - accuracy: 0.4000
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 4.8609 - accuracy: 0.4000
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8573 - accuracy: 0.4000
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8537 - accuracy: 0.4000
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 4.8501 - accuracy: 0.4000
[1 1 1 1 1]
[1. 1. 1. 1. 1.]


## Now, Your turn!

In [24]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [25]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [27]:
x.shape, y.shape

((40,), (40,))

In [29]:
# 1. 모델 초기화
keras.backend.clear_session()

# 2. 모델 설정
model = keras.models.Sequential()

# 3. 모델 추가
model.add(keras.layers.Input(1))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 4. 모델 컴파일
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
# 5. 모델 훈련
model.fit(x,y, epochs=10)

Epoch 1/10
2/2 [==============================] - 1s 5ms/step - loss: 1.1939 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 4ms/step - loss: 1.1842 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 4ms/step - loss: 1.1749 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 4ms/step - loss: 1.1650 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 6ms/step - loss: 1.1560 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 4ms/step - loss: 1.1465 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 5ms/step - loss: 1.1373 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 4ms/step - loss: 1.1274 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 6ms/step - loss: 1.1192 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 3ms/step - loss: 1.1096 - accuracy: 0.5250


In [31]:
print(y[:5])
print(model.predict(x[:5]).reshape(-1))

[0 0 0 0 0]
[0.49504423 0.547707   0.59932286 0.648825   0.6953205 ]
