# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [5]:
# 1. 모델 초기화
keras.backend.clear_session()

# 2. 모델 생성
model = keras.models.Sequential()

# 3. 모델 추가 : .add
model.add(keras.Input(13,))
model.add(keras.layers.Dense(1))

# 4. 모델 컴파일
model.compile(loss='mse', optimizer='adam')

In [6]:
# 5. 모델 훈련
model.fit(x,y, epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 42398.8867
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 36711.3320
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 31574.5703
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 27000.6816
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 22990.5449
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 19487.2832
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 16448.2422
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 13825.6553
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 11601.5947
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 9707.0557


In [7]:
# 6. 예측
y_pred = model.predict(x)
print(y_pred[:5].reshape(-1))
print(y[:5].reshape(-1))

[135.78743  137.02278  129.8862   123.67026  127.125946]
[24.  21.6 34.7 33.4 36.2]


# Logistic Regression 쬐금 더 어려운 데이터

In [8]:
from sklearn.datasets import load_breast_cancer

In [9]:
cancer = load_breast_cancer()

In [11]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [15]:
# 1. model 초기화
keras.backend.clear_session()

# 2. model 생성
model = keras.models.Sequential()

# 3. model 추가
model.add(keras.layers.Input(30,))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 4. model 컴파일
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
# 5. 모델 훈련
model.fit(x, y, epochs=10)

Epoch 1/10
18/18 [==============================] - 1s 2ms/step - loss: 82.3845 - accuracy: 0.6274
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 64.1861 - accuracy: 0.6274
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 45.9922 - accuracy: 0.6221
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 28.0468 - accuracy: 0.5044
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 18.4687 - accuracy: 0.1213
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 16.8505 - accuracy: 0.1388
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 16.0424 - accuracy: 0.1529
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 15.2271 - accuracy: 0.1388
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 14.3759 - accuracy: 0.1371
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 13.5793 - accuracy: 0.1547


In [23]:
y_pred = model.predict(x)
y_pred = np.where(y_pred>=0.5, 1, 0)

In [24]:
print(y_pred[:5].reshape(-1))
print(y[:5])

[1 1 1 0 1]
[0 0 0 0 0]
