# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [5]:
# 1. 모델 초기화
keras.backend.clear_session()

# 2. 레이어 생성
input_layer = keras.layers.Input(shape=(13,))
output_layer = keras.layers.Dense(1)(input_layer)

# 3. 모델 생성
model = keras.models.Model(input_layer, output_layer)

# 4. 모델 컴파일
model.compile(loss=keras.losses.mse, optimizer='adam')

In [6]:
# 5. 모델 훈련
model.fit(x, y, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 88155.0938
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 79770.4219
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 71912.2109
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 64655.7070
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 57921.0469
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 51878.5898
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 46247.5195
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 41128.1484
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 36479.9766
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 32330.8926


In [8]:
# 6. 모델 예측
y_pred = model.predict(x)
print(y_pred[:5].reshape(-1))
print(y[:5])

[143.49461  120.00642  127.23321  128.03522  124.557945]
[24.  21.6 34.7 33.4 36.2]


# Logistic Regression 쬐금 더 어려운 데이터

In [9]:
from sklearn.datasets import load_breast_cancer

In [10]:
cancer = load_breast_cancer()

In [12]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [16]:
# 1. 모델 초기화
keras.backend.clear_session()

# 2. 레이어 생성
input_layer = keras.layers.Input(shape=(30,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 3. 모델 생성
model = keras.models.Model(input_layer, output_layer)

# 4. 모델 컴파일
model.compile(loss=keras.losses.binary_crossentropy, metrics=['accuracy'], optimizer='adam')

In [17]:
# 5. 모델 훈련
model.fit(x,y, epochs=10)

Epoch 1/10
18/18 [==============================] - 0s 2ms/step - loss: 290.4050 - accuracy: 0.6274
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 271.5413 - accuracy: 0.6274
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 253.4870 - accuracy: 0.6274
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 234.5977 - accuracy: 0.6274
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 216.5184 - accuracy: 0.6274
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 197.8614 - accuracy: 0.6274
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 179.6722 - accuracy: 0.6274
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 161.1841 - accuracy: 0.6274
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 142.7135 - accuracy: 0.6274
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 124.4062 - accuracy: 0.6274

In [18]:
# 6. 모델 평가
y_pred = model.predict(x)
y_pred = np.where(y_pred >=0.5, 1, 0)
print(y_pred[:5].reshape(-1))
print(y[:5])

[1 1 1 1 1]
[0 0 0 0 0]
