# 멀티클래스 분류 연습 (over 2진분류)

![iris_flower](https://media.istockphoto.com/photos/purple-iris-flowers-picture-id974833780?k=6&m=974833780&s=612x612&w=0&h=xANkJjTqlLuJUMLE0qNXjRUqXtr3b428xFm0IgZW8Kc=)

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

In [8]:
y = to_categorical(y, 3)

In [9]:
x.shape, y.shape

((150, 4), (150, 3))

# 1번. Sequential API style로 모델링 하세요

    loss = 'categorical_crossentropy' 사용!

In [10]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [11]:
# 1. 모델 초기화
keras.backend.clear_session()

# 2. 모델 생성
model = keras.models.Sequential()

# 3. 모델 추가
model.add(keras.layers.Input(4,))
model.add(keras.layers.Dense(3, activation='softmax'))

# 4. 모델 컴파일
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [12]:
# 5. 모델 훈련
model.fit(x,y, epochs=10)

Epoch 1/10
5/5 [==============================] - 1s 2ms/step - loss: 3.0214 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 2.9615 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 2.9040 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 2.8478 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 2.7913 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 2.7361 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 2.6819 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 2.6302 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 2.5773 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 2.5294 - accuracy: 0.3333


In [13]:
y_pred = model.predict(x)
# y_pred = y_pred.argmax(axis=1)
y_pred[:5]

array([[0.00925202, 0.8540432 , 0.13670468],
       [0.01398309, 0.79857403, 0.1874429 ],
       [0.01324802, 0.8295379 , 0.15721403],
       [0.01650594, 0.76441723, 0.21907683],
       [0.00924625, 0.8573047 , 0.13344915]], dtype=float32)

In [14]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

# 2번. Functional API style로 모델링 하세요

In [15]:
x.shape, y.shape

((150, 4), (150, 3))

In [16]:
# 1. 모델 초기화
keras.backend.clear_session()

# 2. 레이어 생성
input_layer = keras.layers.Input(shape=(4,))
output_layer = keras.layers.Dense(3, activation='softmax')(input_layer)

# 3. 모델 생성
model = keras.models.Model(input_layer, output_layer)

# 4. 컴파일
model.compile(loss=keras.losses.categorical_crossentropy, metrics=['accuracy'], optimizer='adam')

In [20]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [17]:
# 5. 모델 훈련
model.fit(x, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 8.5885 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 8.4780 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 8.3703 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 8.2587 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 8.1506 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 8.0433 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 7.9303 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 7.8188 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 7.7133 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 7.6028 - accuracy: 0.3333


In [19]:
# 6. 모델 평가
y_pred = model.predict(x)
print(y_pred[:5])
print(y[:5])

[[0.99560213 0.00133205 0.00306589]
 [0.9948053  0.00223415 0.00296057]
 [0.9931271  0.00223617 0.00463678]
 [0.99323684 0.00270931 0.00405386]
 [0.99500316 0.00134607 0.00365082]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
