# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()

In [3]:
x = cancer.data
y = cancer.target

In [4]:
x.shape, y.shape

((569, 30), (569,))

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2022)

In [6]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [7]:
########
# 모델링
########
# 1. 초기화
keras.backend.clear_session()

# 2. 레이어 생성
input_layer = keras.layers.Input(shape=(30,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 3. 모델 생성
model = keras.models.Model(input_layer, output_layer)

# 4. 컴파일
model.compile(loss=keras.losses.binary_crossentropy, metrics=['accuracy'], optimizer=keras.optimizers.Adam())

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [8]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, validation_split=0.2)


Epoch 1/10
12/12 [==============================] - 1s 23ms/step - loss: 179.2457 - accuracy: 0.6209 - val_loss: 145.4813 - val_accuracy: 0.6923
Epoch 2/10
12/12 [==============================] - 0s 5ms/step - loss: 167.0868 - accuracy: 0.6209 - val_loss: 135.2144 - val_accuracy: 0.6923
Epoch 3/10
12/12 [==============================] - 0s 5ms/step - loss: 154.5747 - accuracy: 0.6209 - val_loss: 125.3280 - val_accuracy: 0.6923
Epoch 4/10
12/12 [==============================] - 0s 5ms/step - loss: 142.4299 - accuracy: 0.6209 - val_loss: 115.4703 - val_accuracy: 0.6923
Epoch 5/10
12/12 [==============================] - 0s 4ms/step - loss: 130.3408 - accuracy: 0.6209 - val_loss: 105.2594 - val_accuracy: 0.6923
Epoch 6/10
12/12 [==============================] - 0s 4ms/step - loss: 117.4632 - accuracy: 0.6209 - val_loss: 95.3074 - val_accuracy: 0.6923
Epoch 7/10
12/12 [==============================] - 0s 5ms/step - loss: 105.0839 - accuracy: 0.6209 - val_loss: 85.0821 - val_accuracy: 

In [9]:
###########
# 모델 예측
###########
from sklearn.metrics import classification_report

y_pred = model.predict(x_test)
y_pred = np.where(y_pred>=0.5, 1, 0)

print(y_pred[:5].reshape(-1))
print(y_test[:5])

[1 1 1 1 1]
[1 1 0 1 1]


# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [10]:
########
# 모델링
########
# 1. 초기화
keras.backend.clear_session()

# 2. 레이어 생성
input_layer = keras.layers.Input(shape=(30,))
first_layer = keras.layers.Dense(32, activation='relu')(input_layer)
second_layer = keras.layers.Dense(32, activation='relu')(first_layer)
output_layer = keras.layers.Dense(1, activation='sigmoid')(second_layer)

# 3. 모델 생성
model = keras.models.Model(input_layer, output_layer)

# 4. 컴파일
model.compile(loss=keras.losses.binary_crossentropy, metrics=['accuracy'], optimizer=keras.optimizers.Adam())

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [11]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=10, validation_split=0.2)

Epoch 1/10
12/12 [==============================] - 1s 18ms/step - loss: 27.2309 - accuracy: 0.5934 - val_loss: 7.2469 - val_accuracy: 0.1429
Epoch 2/10
12/12 [==============================] - 0s 6ms/step - loss: 8.6533 - accuracy: 0.3407 - val_loss: 7.8763 - val_accuracy: 0.3077
Epoch 3/10
12/12 [==============================] - 0s 5ms/step - loss: 4.7660 - accuracy: 0.3736 - val_loss: 2.5149 - val_accuracy: 0.4286
Epoch 4/10
12/12 [==============================] - 0s 5ms/step - loss: 1.6839 - accuracy: 0.3929 - val_loss: 0.6280 - val_accuracy: 0.7033
Epoch 5/10
12/12 [==============================] - 0s 5ms/step - loss: 0.6057 - accuracy: 0.7527 - val_loss: 0.5056 - val_accuracy: 0.7363
Epoch 6/10
12/12 [==============================] - 0s 5ms/step - loss: 0.4508 - accuracy: 0.8489 - val_loss: 0.3106 - val_accuracy: 0.8901
Epoch 7/10
12/12 [==============================] - 0s 5ms/step - loss: 0.3815 - accuracy: 0.8544 - val_loss: 0.2787 - val_accuracy: 0.8901
Epoch 8/10
12/12 [

In [12]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred = np.where(y_pred>= 0.5, 1, 0)
print(y_pred[:5].reshape(-1))
print(y_test[:5])

[1 1 1 1 1]
[1 1 0 1 1]
